name: Сборка Python-библиотеки
on:
  push:
jobs:
  build-test:
    name: Build immunity agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        run: |
          apt-get update
          apt-get install -y python3 python3-pip python3-venv
      - name: Build agent
        run: |
          python3 -m pip install --upgrade build
          python3 -m build
